project:
  type: website
  output-dir: docs

website:
  title: "Mary Cadogan"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - GISproject.qmd
      - Naturewriting.qmd
      - Outside-school.qmd

format:
  html:
    theme: 
      light: morph
      dark: slate
    css: styles.css
    page-layout: full

editor: visual


