project:
  type: website
  output-dir: docs

website:
  title: "Mary Cadogan"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - GISproject.qmd
      - abroad.qmd
      - Research-presentation.qmd
    right: 
     - icon: github
       href: https://github.com/mary-cadogan
     - icon: linkedin
       href: https://www.linkedin.com/in/mary-cadogan-a808a9196/
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Mary Cadogan"

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Roboto Condensed
    toc: true
    page-layout: full

editor: visual


